import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-pharmacy-acquisition-reimbursement-margin-recovery",
  "engine": "recovery",
  "title": "Pharmacy Acquisition Cost & Reimbursement Margin Recovery",
  "shortTitle": "Pharmacy Margin Recovery",
  "tagline": "Reconcile drug acquisition cost, claim reimbursement, dispensing economics, and appeal opportunities",
  "industry": "Pharmacy Revenue Integrity",
  "uiPort": 4575,
  "apiPort": 5575,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Negative-margin prescriptions identified, appealed, corrected, and converted into sustainable pharmacy margin",
  "valueNarrative": "Unify NDCs, wholesaler invoices, rebates, payer claims, remittances, benchmarks, reversals, and appeals at prescription level.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "supportedReimbursement",
    "actualLabel": "Received Reimbursement",
    "expectedLabel": "Supported Reimbursement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Drug acquisition, benchmark, claim, and remittance evidence indicate recoverable pharmacy margin.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("ndc-and-drug-registry","PMR01","NDC and drug registry","Reconcile ndc and drug registry using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed ndc and drug registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","NDC and drug registry Reference","text","PMR01-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("wholesaler-invoice-ingestion","PMR02","Wholesaler invoice ingestion","Reconcile wholesaler invoice ingestion using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed wholesaler invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Wholesaler invoice ingestion Reference","text","PMR02-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("contract-acquisition-cost-calculation","PMR03","Contract acquisition-cost calculation","Reconcile contract acquisition-cost calculation using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed contract acquisition-cost calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Contract acquisition-cost calculation Reference","text","PMR03-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("rebate-and-allowance-accrual","PMR04","Rebate and allowance accrual","Reconcile rebate and allowance accrual using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed rebate and allowance accrual decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Rebate and allowance accrual Reference","text","PMR04-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("claim-and-remittance-ingestion","PMR05","Claim and remittance ingestion","Reconcile claim and remittance ingestion using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed claim and remittance ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Claim and remittance ingestion Reference","text","PMR05-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("ingredient-cost-validation","PMR06","Ingredient-cost validation","Reconcile ingredient-cost validation using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed ingredient-cost validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Ingredient-cost validation Reference","text","PMR06-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("dispensing-fee-validation","PMR07","Dispensing-fee validation","Reconcile dispensing-fee validation using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed dispensing-fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Dispensing-fee validation Reference","text","PMR07-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("benchmark-comparison","PMR08","Benchmark comparison","Reconcile benchmark comparison using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed benchmark comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Benchmark comparison Reference","text","PMR08-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("negative-margin-detection","PMR09","Negative-margin detection","Reconcile negative-margin detection using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed negative-margin detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Negative-margin detection Reference","text","PMR09-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("mac-appeal-eligibility","PMR10","MAC appeal eligibility","Reconcile mac appeal eligibility using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed mac appeal eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","MAC appeal eligibility Reference","text","PMR10-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("reversal-and-rebill-analysis","PMR11","Reversal and rebill analysis","Reconcile reversal and rebill analysis using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed reversal and rebill analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Reversal and rebill analysis Reference","text","PMR11-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("specialty-margin-analysis","PMR12","Specialty margin analysis","Reconcile specialty margin analysis using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed specialty margin analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Specialty margin analysis Reference","text","PMR12-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("wholesaler-credit-reconciliation","PMR13","Wholesaler credit reconciliation","Reconcile wholesaler credit reconciliation using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed wholesaler credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Wholesaler credit reconciliation Reference","text","PMR13-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("payer-appeal-generation","PMR14","Payer appeal generation","Reconcile payer appeal generation using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed payer appeal generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Payer appeal generation Reference","text","PMR14-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("recovered-margin-ledger","PMR15","Recovered margin ledger","Reconcile recovered margin ledger using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed recovered margin ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Recovered margin ledger Reference","text","PMR15-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]}),
feature("drug-payer-and-location-analytics","PMR16","Drug payer and location analytics","Reconcile drug payer and location analytics using NDC product data, wholesaler invoices, acquisition contracts, rebates, claims, remittances, NADAC and MAC benchmarks, reversals, and appeal rules.","Produce a governed drug payer and location analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payerPrescription","Payer / Prescription","text","Apex PBM / RX-884120"],["caseReference","Drug payer and location analytics Reference","text","PMR16-2026-001"],["reimbursedAmount","Received Reimbursement","currency",284000],["supportedReimbursement","Supported Reimbursement","currency",347500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Retail pharmacy portfolio","Specialty pharmacy claim","Health-system outpatient pharmacy","High-cost generic cohort","Brand drug reimbursement"]})
]);
